services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  CucumberLinter\:
    resource: '../src/'

  CucumberLinter\Linter:
    factory: ['CucumberLinter\Linter', 'getInstance']

  CucumberLinter\Console\Application:
    public: true
    arguments:
      - !tagged command

