name: "Compile PHAR"

on:
  pull_request:
  push:
    branches:
      - "0.1.x"
    tags:
      - '0.1.*'

# github.head_ref is only set when the workflow was triggered by a pull_request and it contains the value of the source branch of the PR.
# github.ref_name will than only be used if the workflow was not triggered by a pull_request and it also just contains the branch name.
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

concurrency:
  group: phar-${{ github.ref }} # will be canceled on subsequent pushes in both branches and pull requests
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    outputs:
      checksum: ${{ steps.checksum.outputs.md5 }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.2"
          extensions: mbstring, intl

      - name: "Install dependencies"
        run: "composer install --no-dev --no-interaction --no-progress"

      - name: "Compile PHAR"
        working-directory: "build"
        run: "php box.phar compile --no-parallel"

      - uses: actions/upload-artifact@v3
        with:
          name: phar-file
          path: tmp/cucumber-linter.phar

      - name: "Run PHAR"
        run: "tmp/cucumber-linter.phar --help"

      - name: "Delete PHAR"
        run: "rm tmp/cucumber-linter.phar"

      - name: "Set autoloader suffix"
        run: "composer config autoloader-suffix CucumberLinterChecksum"

      - name: "Composer dump"
        run: "composer dump-autoload --no-dev --no-interaction"

      - name: "Set timestamp for PHAR checksum"
        working-directory: "build"
        run: echo $(jq '. += {"timestamp":"2023-11-25 16:55"}' box.json) > box.json

      - name: "Compile PHAR for checksum"
        working-directory: "build"
        run: "php box.phar compile --no-parallel"
        env:
          COMPOSER_ROOT_VERSION: "${{ env.BRANCH_NAME }}-dev"

      - name: "Unset autoloader suffix"
        run: "composer config autoloader-suffix --unset"

      - name: "Unset timestamp for PHAR checksum"
        working-directory: "build"
        run: echo $(jq 'del(.timestamp)' test.json) > test.json

      - name: "Save checksum"
        id: "checksum"
        run: echo "md5=$(md5sum tmp/cucumber-linter.phar | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: phar-file-checksum
          path: tmp/cucumber-linter.phar

      - name: "Delete checksum PHAR"
        run: "rm tmp/cucumber-linter.phar"

  commit:
    name: "Commit PHAR"
    if: "github.repository_owner == 'kingdutch' && github.event_name != 'pull_request'"

    needs: build
    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: "Create .ssh directory"
        run: mkdir -p ~/.ssh

      - name: "Import SSH Key"
        run: echo "${{ secrets.SSH_CUCUMBER_LINTER_BOT_PRIVATE_KEY }}" > ~/.ssh/signing_key && chmod 600 ~/.ssh/signing_key

      - name: "Create allowed signers file"
        run: echo "cucumber-linter-bot@alexandervarwijk.com ${{ secrets.SSH_CUCUMBER_LINTER_BOT_PUBLIC_KEY }}" > ~/.ssh/allowed_signers

      - name: "Checkout cucumber-linter-dist"
        uses: actions/checkout@v4
        with:
          repository: kingdutch/cucumber-linter
          path: cucumber-linter-dist
          token: ${{ secrets.CUCUMBER_LINTER_BOT_TOKEN }}
          ref: ${{ env.BRANCH_NAME }}

      - name: "Get previous pushed dist commit"
        id: previous-commit
        working-directory: cucumber-linter-dist
        run: echo "sha=$(sed -n '2p' .phar-checksum)" >> $GITHUB_OUTPUT

      - name: "Checkout cucumber-linter-src"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: cucumber-linter-src

      - name: "Get Git log"
        id: git-log
        working-directory: cucumber-linter-src
        run: |
          echo "log<<MESSAGE" >> $GITHUB_OUTPUT
          echo "$(git log ${{ steps.previous-commit.outputs.sha }}..${{ github.event.after }} --reverse --pretty='https://github.com/kingdutch/cucumber-linter-src/commit/%H %s')" >> $GITHUB_OUTPUT
          echo 'MESSAGE' >> $GITHUB_OUTPUT

      - name: "Get short cucumber-linter-src SHA"
        id: short-src-sha
        working-directory: cucumber-linter-src
        run: echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: "Check PHAR checksum"
        id: checksum-difference
        working-directory: cucumber-linter-dist
        run: |
          checksum=${{needs.build.outputs.checksum}}
          if [[ $(head -n 1 .phar-checksum) != "$checksum" ]]; then
            echo "result=different" >> $GITHUB_OUTPUT
          else
            echo "result=same" >> $GITHUB_OUTPUT
          fi

      - name: "Download cucumber-linter.phar"
        uses: actions/download-artifact@v3
        with:
          name: phar-file

      - name: "mv PHAR"
        run: mv cucumber-linter.phar cucumber-linter-dist/cucumber-linter.phar

      - name: "chmod PHAR"
        run: chmod 755 cucumber-linter-dist/cucumber-linter.phar

      - name: "Update checksum"
        run: |
          echo ${{ needs.build.outputs.checksum }} > cucumber-linter-dist/.phar-checksum
          echo ${{ github.event.head_commit.id }} >> cucumber-linter-dist/.phar-checksum

      - name: "Sign PHAR"
        working-directory: cucumber-linter-dist
        run: rm cucumber-linter.phar.sig && ssh-keygen -Y sign -f ~/.ssh/signing_key -n file cucumber-linter.phar

      - name: "Verify PHAR"
        working-directory: cucumber-linter-dist
        run: "ssh-keygen -Y verify -f ~/.ssh/allowed_signers -I cucumber-linter-bot@alexandervarwijk.com -n file -s cucumber-linter.phar.sig < cucumber-linter.phar"

      - name: "Install lucky_commit"
        uses: baptiste0928/cargo-install@v2
        with:
          crate: lucky_commit
          args: --no-default-features

      - name: "Commit PHAR - development"
        if: "!startsWith(github.ref, 'refs/tags/') && steps.checksum-difference.outputs.result == 'different'"
        working-directory: cucumber-linter-dist
        env:
          INPUT_LOG: ${{ steps.git-log.outputs.log }}
        run: |
          git config --global user.name "cucumber-linter-bot"
          git config --global user.email "cucumber-linter-bot@alexandervarwijk.com"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/signing_key
          git add .
          git commit -S -m "Updated Cucumber Linter to commit ${{ github.event.after }}" -m "$INPUT_LOG" --author "cucumber-linter-bot <cucumber-linter-bot@alexandervarwijk.com>"
          lucky_commit ${{ steps.short-src-sha.outputs.sha }}
          git push

      - name: "Commit PHAR - tag"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "cucumber-linter-bot"
          commit_user_email: "cucumber-linter-bot@alexandervarwijk.com"
          commit_author: "cucumber-linter-bot <cucumber-linter-bot@alexandervarwijk.com>"
          commit_options: "-S"
          repository: cucumber-linter-dist
          commit_message: "Cucumber Linter ${{github.ref_name}}"
          tagging_message: ${{github.ref_name}}
